name: Sub-issue
description: File a sub-issue.
title: "[Provide a short descriptive title]"
labels: ["sub-issue", "triage"]
projects: ["qbicsoftware/25"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this sub-issue report!
  - type: textarea
    id: what-is-it-about
    attributes:
      label: What's the issue?
      description: What part of the parent-issue is addressed here?
      placeholder: What is the sub-issue about?
      value: "A sub-issue to organise bigger issues into smaller parts."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/qbicsoftware/data-manager-app?tab=coc-ov-file).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
