# This workflow will build a package using Maven and then publish it to
# qbic-repo.qbic.uni-tuebingen.de packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploy Snapshot

on:
  push:
    branches:
      - development

jobs:
  publish_snapshot:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          settings-path: ${{ github.workspace }}

      - name: Load local Maven repository cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Remove existing snapshot tags which are not supposed to be present
      - name: Remove snapshot tags
        run: mvn versions:set -DremoveSnapshot
      # Set the SNAPSHOT for this build and deployment
      - name: Set version in Maven project
        run: mvn versions:set -DnewVersion='${project.version}-SNAPSHOT'

      - name: Build with Maven
        run: VAADIN_OFFLINE_KEY=${{ secrets.VAADIN_SERVER_23_2 }} mvn -B package -Pproduction -Dvaadin.force.production.build=true --file pom.xml

      - name: Publish artefact to QBiC Nexus Repository
        run: mvn --settings $GITHUB_WORKSPACE/.github.settings.xml deploy
        env:
          MAVEN_REPO_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_REPO_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
