name: Run Maven Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, master ]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Debug OIDC (get a token)
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sigstore'); // audience example
            core.setSecret(token);
            console.log('OIDC token acquired. Length:', token.length);
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          settings-path: ${{ github.workspace }}

      - name: Load local Maven repository cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn clean verify
